apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-iufm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-iufm
    app.kubernetes.io/part-of: tkrw-pr712-0075-0062-app
  name: devfile-sample-iufm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-iufm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-iufm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0062-tenant/tkrw-pr712-0075-0062-app/devfile-sample-iufm@sha256:1e953ca345f43700efb3ad37cf8923fb83a20e0793407567b6b4f90c82b65d65
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
